sever:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chapter_db
    username: chapter.user
    password: chapter-backend
    class: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

aws:
  region:
    static: sa-east-1
    auto: false
  sqs:
    queueUrl: http://localhost:4566/000000000000/chapter
    delaySeconds: 15
    accessKey: teste-chapter
    secretAccessKey: teste-chapter